[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildArgs = { NEXT_PUBLIC_API_URL = "${{NEXT_PUBLIC_API_URL}}", NEXT_PUBLIC_WS_URL = "${{NEXT_PUBLIC_WS_URL}}" }

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 60
