"""initial

Revision ID: a83547bb0e90
Revises: 
Create Date: 2026-05-28 14:21:18.851005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a83547bb0e90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('intent', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'building', 'validating', 'active', 'paused', 'failed', 'awaiting_approval', name='workflowstatus'), nullable=False),
    sa.Column('graph_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('canvas_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('template_name', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('memory_type', sa.Enum('none', 'short_term', 'long_term', name='memorytype'), nullable=False),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('guardrails', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interaction_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_workflow_id'), 'agents', ['workflow_id'], unique=False)
    op.create_table('genesis_builds',
    sa.Column('intent', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('decomposing', 'building', 'critiquing', 'validating', 'awaiting_approval', 'deployed', 'failed', name='buildstatus'), nullable=False),
    sa.Column('architect_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decomposer_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('builder_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('critic_feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validator_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genesis_builds_workflow_id'), 'genesis_builds', ['workflow_id'], unique=False)
    op.create_table('runs',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', 'cancelled', name='runstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('token_count_total', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_workflow_id'), 'runs', ['workflow_id'], unique=False)
    op.create_table('messages',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('sender_agent', sa.String(), nullable=False),
    sa.Column('receiver_agent', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('state_update', 'tool_call', 'tool_result', 'human_input', 'agent_output', name='messagetype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_run_id'), 'messages', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_run_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_runs_workflow_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_genesis_builds_workflow_id'), table_name='genesis_builds')
    op.drop_table('genesis_builds')
    op.drop_index(op.f('ix_agents_workflow_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_table('workflows')
    # ### end Alembic commands ###
